# Generated by Django 4.0 on 2022-06-06 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.EmailField(max_length=100, null=True)),
                ('name', models.TextField(max_length=50, null=True)),
                ('description', models.TextField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('url', models.URLField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
