# Generated by Django 4.0 on 2022-06-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
