# Generated by Django 4.0 on 2022-06-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
