# Generated by Django 4.0 on 2022-06-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_knowledge_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Knowledge',
            new_name='Skill',
        ),
    ]
