# Generated by Django 4.0 on 2022-06-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_skill_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.ManyToManyField(to='knowledge.Tag'),
        ),
    ]
