# Generated by Django 4.0 on 2022-06-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_alter_skill_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
