# Generated by Django 4.0 on 2022-06-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_alter_category_slug_alter_skill_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['updated_at']},
        ),
    ]
